Neos:
  Neos:
    fusion:
      autoInclude:
        'Gmedia.CoreSite': TRUE
  Form:
    presets:
      default:
        title: 'LeitSatz'
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              layoutPathPattern: 'resource://Gmedia.CoreSite/Private/Form/Layouts/{@type}.html'
          'Neos.Form:Form':
            renderingOptions:
              renderableNameInTemplate: form
              previousButtonClassAttribute: 'btn btn-cancel'
              nextButtonClassAttribute: 'btn btn-primary'
              submitButtonClassAttribute: 'btn btn-primary'
              templatePathPattern: 'resource://Gmedia.CoreSite/Private/Form/{@type}.html'
          'Neos.Form:FormElement':
            properties:
              containerClassAttribute: 'form-group'
              elementClassAttribute: 'form-control'
              elementErrorClassAttribute: 'form-control-danger'
          'Neos.Form:MultiLineText':
            properties:
              elementClassAttribute: 'form-control'    
              
Gmedia:
  CoreSite:
    Fusion:
      Prototypes:
        ResponsivePictureTag:
          useHolderJS: false
          useLazyload: false
    apiKeys:
      google: "AIzaSyD5P6w4K2JP2_8RDoc4h75wZeeMwA4jPls"