Neos:
  Neos:
    fusion:
      autoInclude:
        'Gmedia.CoreSite': TRUE
  Form:
    presets:
      default:
        formElementTypes:
          'Neos.Form:Base':
            renderingOptions:
              templatePathPattern: 'resource://Gmedia.CoreSite/Private/Form/{@type}.html'
              partialPathPattern: 'resource://Gmedia.CoreSite/Private/Form/Partials/{@type}.html'
              layoutPathPattern: 'resource://Gmedia.CoreSite/Private/Form/Layouts/{@type}.html'
          'Neos.Form:FormElement':
            properties:
              containerClassAttribute: 'input'
              elementClassAttribute: 'gc-form-control'
              elementErrorClassAttribute: 'form-control-danger'
              
Gmedia:
  CoreSite:
    apiKeys:
      google: "AIzaSyD5P6w4K2JP2_8RDoc4h75wZeeMwA4jPls"